name: nextbestie_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_flavorizr: ^2.3.1
  figma_squircle: ^0.6.3
  flutter_animate: ^4.5.2
  flutter_secure_storage: ^9.2.4
  firebase_remote_config: ^5.4.7
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  package_info_plus: ^8.3.0
  precached_network_image: ^1.2.4
  intl: ^0.20.2
  get: ^4.7.2
  supabase_flutter: ^2.8.0
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  country_picker: ^2.0.26
  image_picker: ^1.1.2
  flutter_card_swiper: ^7.0.2
  dio: ^5.8.0+1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
